### ISSUE TITLE
Duplicate comment

### ISSUE THREAD

**Issue by Akryum** [volta-net/feedback#9] opened 2022-10-20 11:58 UTC
I've just sent a comment on an issue, and it appears twice in Volta (once on GitHub):
![image](https://user-images.githubusercontent.com/2798204/196942344-7883ee7a-57a4-41b2-8a7a-dad9087f3dd0.png)

https://github.com/vuejs/devtools/issues/1950#issuecomment-1285398129

**Comment by benjamincanac** [comment] 2022-10-20 12:24
Hello @Akryum, 

We've noticed this too, the issue will be fixed soon!

**Comment by benjamincanac** [comment] 2022-10-20 15:35
The issue is now fixed and all duplicated comments should have been removed. Let me know if this happens again.

**Closed by benjamincanac** 2022-10-20 15:35 UTC
